version: 0.2

phases:
  install:
    commands:
      -
  pre_build:
    commands:
      - mkdir ~/.gradle/
      - echo cacheUser = $CACHE_USER > ~/.gradle/gradle.properties
      - echo cachePassword = $CACHE_PASSWORD >> ~/.gradle/gradle.properties
  build:
    commands:
      - echo Build started on `date`
      - chmod a+x gradlew
      - ls -la
      - ./gradlew clean build --info --no-daemon
      - mv 
  post_build:
    commands:
      - echo Build completed on `date`
      - JAR_VERSION=`python getVersion`
      - ./gradlew publish -PjarVersion $JAR_VERSION
cache:
  paths:
    - '/root/.gradle/wrapper/**/*'
