version: 0.2

phases:
  install:
    commands:
      -
  pre_build:
    commands:
      - mkdir ~/.gradle/
      - echo cacheUser = $CACHE_USER > ~/.gradle/gradle.properties
      - echo cachePassword = $CACHE_PASSWORD >> ~/.gradle/gradle.properties
  build:
    commands:
      - echo Build started on `date`
      - chmod a+x gradlew
      - ls -la
      - ./gradlew build --info --no-daemon -x bootJar
  post_build:
    commands:
      - echo Build completed on `date`
      - chmod +x /usr/local/scripts/python/getVersion
      - AWS_RESPONSE=`aws secretsmanager get-secret-value --secret-id zevrant-security-common-version`
      - JAR_VERSION=`python /usr/local/scripts/python/getVersion $AWS_RESPONSE`
      - ./gradlew publish -PjarVersion $JAR_VERSION
cache:
  paths:
    - '/root/.gradle/wrapper/**/*'
